### ISSUE TITLE
Probando Js_Notify

### ISSUE THREAD

**Issue by LucasPadovan** [gagoar/SrBuj#6]
En el controlador:
      js_notify(message: 'notificacion', time: 4000, side: 'right')
      render @intervention_type, content_type: 'text/html'

Cuando se ejecuta el método
· la notificación sigue apareciendo en la izquierda
· luego de los 4 segundos, la clase srbuj-notify desaparece, pero, la notificación sigue mostrandose
· el texto aparece tachado con una linea horizontal.

Miscelaneos:

El atributo TYPE que se le puede setear, recibe clases definidas en css... cambiar el nombre por "class" podría mejorar el entendimiento del atributo.

**Comment by gagoar** [comment]
todo eso es por que no agregaste al manifesto de stylesheets SrBuj.
Esta aplicando los estilos por defecto para el elemento que se utiliza para mostar los efectos.

**Comment by LucasPadovan** [comment]
Algo parecido, los assets se estaban tomando desde cache y no estaban actualizados. Solved ;)
