### ISSUE TITLE
I18n + Encoding + js_notify

### ISSUE THREAD

**Issue by LucasPadovan** [gagoar/SrBuj#8]
Acá te paso los datos de como esta hecho la renderización del js_notify y la salida que obtengo en Chrome y Firefox:

https://gist.github.com/LucasPadovan/6837012

Adjunto una captura del navegador en el momento del error:

![captura de pantalla de 2013-10-05 02 20 49](https://f.cloud.github.com/assets/993291/1274183/f8f2f732-2d7d-11e3-8ac6-607881222c8c.png)

Espero que te sirva de ayuda para encontrar una posible solución a esto y que sea lo que habias pensado a la mañana ;)

No hay ninguna clase de apuro con esto ya que los usuarios y entornos donde se va a usar esta aplicación están controlados y casi seguro va a ser usado con Chrome.

Saludos!

**Comment by gagoar** [comment]
thanks. I will fix it shortly.
hold on tight.

**Comment by LucasPadovan** [comment]
:+1:
